# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
