# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttested',
            name='amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
