# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20161222_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipe',
            new_name='recipes',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.Product'),
        ),
    ]
