# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='vote',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
