# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20170208_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categorytested',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categorytested',
            name='test',
        ),
        migrations.RemoveField(
            model_name='directiontested',
            name='place',
        ),
        migrations.RemoveField(
            model_name='directiontested',
            name='time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryTested',
        ),
        migrations.AddField(
            model_name='directiontested',
            name='parameters',
            field=models.ManyToManyField(to='recipes.Parameter'),
        ),
    ]
