# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20170215_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterTested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, null=True)),
                ('directionTested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.DirectionTested')),
            ],
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='value',
        ),
        migrations.AddField(
            model_name='parametertested',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Parameter'),
        ),
    ]
