# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20170215_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directiontested',
            name='parameters',
        ),
        migrations.AddField(
            model_name='directiontested',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parametertested',
            name='directionTested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametersTested', to='recipes.DirectionTested'),
        ),
    ]
