# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20161222_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttested',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
