# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_ingredienttested_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttested',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientsTested', to='recipes.Test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='recipes.Recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredienttested',
            unique_together=set([('test', 'ingredient')]),
        ),
    ]
